//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Tabbles.OutlookAddIn.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Tabbles.OutlookAddIn.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string LabelCancel {
            get {
                return ResourceManager.GetString("LabelCancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No.
        /// </summary>
        public static string LabelNo {
            get {
                return ResourceManager.GetString("LabelNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        public static string LabelOk {
            get {
                return ResourceManager.GetString("LabelOk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Yes.
        /// </summary>
        public static string LabelYes {
            get {
                return ResourceManager.GetString("LabelYes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open in Tabbles.
        /// </summary>
        public static string MenuOpenInTabbles {
            get {
                return ResourceManager.GetString("MenuOpenInTabbles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync all with Tabbles.
        /// </summary>
        public static string MenuSyncWithTabbles {
            get {
                return ResourceManager.GetString("MenuSyncWithTabbles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tabbles search.
        /// </summary>
        public static string MenuTabblesSearch {
            get {
                return ResourceManager.GetString("MenuTabblesSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tag email in Tabbles.
        /// </summary>
        public static string MenuTagUsingTabbles {
            get {
                return ResourceManager.GetString("MenuTagUsingTabbles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure?.
        /// </summary>
        public static string MsgAreYouSure {
            get {
                return ResourceManager.GetString("MsgAreYouSure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Message from Tables add-in.
        /// </summary>
        public static string MsgCaptionTabblesAddIn {
            get {
                return ResourceManager.GetString("MsgCaptionTabblesAddIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Don&apos;t ask again..
        /// </summary>
        public static string MsgDontAskAgain {
            get {
                return ResourceManager.GetString("MsgDontAskAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to import all your existing email
        ///categorization into Tabbles? It may take a few minutes
        ///and it should be super-cool :).
        /// </summary>
        public static string MsgDoYouWantToSync {
            get {
                return ResourceManager.GetString("MsgDoYouWantToSync", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results found..
        /// </summary>
        public static string MsgNoResultsFound {
            get {
                return ResourceManager.GetString("MsgNoResultsFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Synchronization with Tabbles is already running..
        /// </summary>
        public static string MsgSyncIsRunning {
            get {
                return ResourceManager.GetString("MsgSyncIsRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You cannot move e-mailsToMove to another account when Tabbles is not running..
        /// </summary>
        public static string MsgTabblesIsNotRunning {
            get {
                return ResourceManager.GetString("MsgTabblesIsNotRunning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap open_in_tabbles_16_bmp {
            get {
                object obj = ResourceManager.GetObject("open_in_tabbles_16_bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap open_in_tabbles_16_mask {
            get {
                object obj = ResourceManager.GetObject("open_in_tabbles_16_mask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap open_in_tabbles_16_png {
            get {
                object obj = ResourceManager.GetObject("open_in_tabbles_16_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap open_in_tabbles_32 {
            get {
                object obj = ResourceManager.GetObject("open_in_tabbles_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap search_16_bmp {
            get {
                object obj = ResourceManager.GetObject("search_16_bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap search_16_mask {
            get {
                object obj = ResourceManager.GetObject("search_16_mask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap search_32 {
            get {
                object obj = ResourceManager.GetObject("search_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sync_with_tabbles_16_bmp {
            get {
                object obj = ResourceManager.GetObject("sync_with_tabbles_16_bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sync_with_tabbles_16_mask {
            get {
                object obj = ResourceManager.GetObject("sync_with_tabbles_16_mask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap sync_with_tabbles_32 {
            get {
                object obj = ResourceManager.GetObject("sync_with_tabbles_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tag_using_tabbles_16_bmp {
            get {
                object obj = ResourceManager.GetObject("tag_using_tabbles_16_bmp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tag_using_tabbles_16_mask {
            get {
                object obj = ResourceManager.GetObject("tag_using_tabbles_16_mask", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tag_using_tabbles_16_png {
            get {
                object obj = ResourceManager.GetObject("tag_using_tabbles_16_png", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap tag_using_tabbles_32 {
            get {
                object obj = ResourceManager.GetObject("tag_using_tabbles_32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
